name: Ping Render Health Endpoint

on:
  schedule:
    - cron: '* * * * *'

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Call health endpoint
        run: |
          curl -f https://waste-tracker-backend-city.onrender.com/health